---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: net-attach-def-editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: net-attach-def-editor
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
