# permissions for end users to edit overlaynetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: overlaynetwork-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: selfserviceoverlay
    app.kubernetes.io/part-of: selfserviceoverlay
    app.kubernetes.io/managed-by: kustomize
  name: overlaynetwork-editor-role
rules:
- apiGroups:
  - self.service.ovn.org
  resources:
  - overlaynetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self.service.ovn.org
  resources:
  - overlaynetworks/status
  verbs:
  - get
