---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - self.service.ovn.org
  resources:
  - overlaynetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self.service.ovn.org
  resources:
  - overlaynetworks/finalizers
  verbs:
  - update
- apiGroups:
  - self.service.ovn.org
  resources:
  - overlaynetworks/status
  verbs:
  - get
  - patch
  - update
